GRANT CREATE ON DATABASE "medusa-v2" TO medusa;
GRANT USAGE ON SCHEMA public TO medusa;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO medusa;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO medusa;